// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
